name: json_inference
description: A Dart package providing functionality to infer JSON data types.
version: 0.2.0
homepage: https://github.com/hacker1024/json_inference.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lint: ^2.1.2
